# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='urllink',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
