# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_song_urllink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='urllink',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
